version: '2'
services:
  #======================================================
  # APP
  #======================================================
  app:
    container_name: app
    build:
      context: .
#      dockerfile: .docker/images/PHP-5-6_Apache.Dockerfile
#      dockerfile: .docker/images/PHP-7-0_Apache.Dockerfile
      dockerfile: .docker/images/PHP-7-2_Apache.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app:cached
  #======================================================
  # Database
  #======================================================
  db:
    container_name: db
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - .database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=application
#  #======================================================
#  # Mailhog
#  #======================================================
#  mailhog:
#    container_name: mailhog
#    image: mailhog/mailhog
#    ports:
#      - 8025:8025
#  #======================================================
#  # Adminer
#  #======================================================
#  adminer:
#    container_name: adminer
#    image: adminer
#    ports:
#      - 8080:8080